### ISSUE TITLE
System.NullReferenceException in Intuit.Ipp.Core.ServiceContext

### ISSUE THREAD

**Issue by isaachili** [intuit/QuickBooks-V3-DotNET-SDK#122]
`System.NullReferenceException` when trying to invoke a ServiceContext using the following constructor:
~~~csharp
var validator = new OAuth2RequestValidator(token);
var context = new ServiceContext(token, realmId, IntuitServicesType.QBO, validator);
~~~

I believe the issue lies within here:
https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/ee611cbf1501e20bf2fe481b6afa3cfa03e5f151/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.Core/ServiceContext.cs#L187-190

`IppConfiguration` does not seem to be initialised, however, there is an attempt to set `IppConfiguration.Security`, which is where I believe the `System.NullReferenceException` is thrown.

Version:
Assembly Intuit.Ipp.Core, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null

**Comment by nimisha84** [comment]
I think the problem here is that the apptoken is being confused with accessToken. With OAuth2 keys, you will never find an apptoken in your app settings. So, this constructor should have never been used. On our side, this constructor should be marked as deprecated in the next release. This is the fix for this issue. Please use the constructor which have no appToken.
