### ISSUE TITLE
Purpose of DiscoveryClient.Authority

### ISSUE THREAD

**Issue by sm-g** [intuit/QuickBooks-V3-DotNET-SDK#17]
There is some conversion from ctor argument to both Url and Authority:
https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/7f7ee6c04917297587bcb1e9166d205e21bbfd65/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.OAuth2PlatformClient/Client/DiscoveryClient.cs#L84 

Default `Policy.ValidateIssuerName` is true, so I expect that either `new DiscoveryClient("https://developer.intuit.com/.well-known/openid_sandbox_configuration/")` or `new DiscoveryClient("https://oauth.platform.intuit.com/op/v1")` should work.

But there is no https://oauth.platform.intuit.com/op/v1/.well-known/openid_sandbox_configuration/, and https://developer.intuit.com does not match Issuer (https://oauth.platform.intuit.com/op/v1).

There is also very interesting commented https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/7f7ee6c04917297587bcb1e9166d205e21bbfd65/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.OAuth2PlatformClient/Client/DiscoveryClient.cs#L111

So why DiscoveryClient.Authority ever exists?

**Comment by nimisha84** [comment]
When the discovery doc was getting designed there were internal talks of having the same issuer-https://oauth.platform.intuit.com/op/v1 even for discovery. However, due to some internal decisions, this was never done and we continued to use-https://developer.intuit.com/.
Therefore, Authority does not in fact have any use. But we have still kept it, in case we need it in future.
