### ISSUE TITLE
Access revoked webhook?

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#184]
Hi,

Is it possible to set up a webhook to get notified when the access was revoked by the user?

**Comment by nimisha84** [comment]
If your app provides a way to revoke tokens then you will get the response from the revoke api.
https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#revoke-token-disconnect

But, if the disconnect happens due to some other reasons, then existing tokens you have for that user on the backend will start failing with 401 error for any of your api calls. That should be an indication of token revoke/disconnected user.
You can ask the user to connect again/authorize again in that case to get new tokens.

Also read:
 https://help.developer.intuit.com/s/article/Handling-OAuth-token-expiration

**Comment by clement911** [comment]
Understood.
