### ISSUE TITLE
Non required properties should be nullable 

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#190]
We are coming across another headache here with loads of entity properties that should be nullable but instead are non nullable hence we have to deal with default values for ints, datetimes, bools, etc..
Can you please make them nullable? 
All these <ptyName>Specified properties are an old pattern from the early days...

**Comment by nimisha84** [comment]
This is a known issue with the SDK which we had tried to fix in the past but this needed almost like a total rewrite of the SDK because if we wanted to offer these nullable types, it would mean a different SDK with not just only this but also many other things like rewriting the way we handle requests using a better approach like async await etc. and also rewriting all 1100 something tests. Plus, existing devs can't move or use new api minorversion then and we would have to maintain 2 SDKs.
Again, given the status quo of the current SDK which is in maintenance, we want to concentrate on the support for new  GraphQL API support. This is a decision made by leadership.

**Comment by clement911** [comment]
For anyone else that might be interested, [QuickBooksSharp](https://github.com/better-reports/QuickBooksSharp) uses nullable properties

**Comment by rajendradewani** [comment]
> This is a known issue with the SDK which we had tried to fix in the past but this needed almost like a total rewrite of the SDK because if we wanted to offer these nullable types, it would mean a different SDK with not just only this but also many other things like rewriting the way we handle requests using a better approach like async await etc. and also rewriting all 1100 something tests. Plus, existing devs can't move or use new api minorversion then and we would have to maintain 2 SDKs. Again, given the status quo of the current SDK which is in maintenance, we want to concentrate on the support for new GraphQL API support. This is a decision made by leadership.

I think you are selecting the first enum as the default.

I suggest adding one of the following Enums; the first Enum will be used for the default value.
Active
All
Approved

And then the default will automatically change to the first one (alphabetically).
{ All, Deleted, Voided, Draft, Pending, InTransit, Synchronized, SyncError }

or

{ Active, Deleted, Voided, Draft, Pending, InTransit, Synchronized, SyncError }
This way, the correct status will be displayed, and when an object is deleted or voided, you can set the status specifically.
