### ISSUE TITLE
Newtonsoft.Json V10 issues

### ISSUE THREAD

**Issue by dcarl1** [intuit/QuickBooks-V3-DotNET-SDK#4]
I'm experiencing the same issue as this person:

https://stackoverflow.com/questions/43717582/type-exists-in-both-newtonsoft-json-after-update-to-10-0-2

It appears that the Quickbooks API Nuget package causes V9 to be referenced as well as V10, preventing package upgrades.

**Comment by nimisha84** [comment]
Please create a support ticket on developer.intuit.com->Help and I will send you the signed dlls for the SDK so that you can use V10 of Newtonsoft json as well as v9 of what is used in SDK.

**Comment by dcarl1** [comment]
Done - #00047320

Thanks.

**Comment by nimisha84** [comment]
Sent the dlls.

**Comment by sm-g** [comment]
@nimisha84 do you have plan when to update nuget package?

**Comment by dcarl1** [comment]
@sm-g I haven't investigated yet but I believe the issue is Intuits dlls carry around newtonsoft as an embedded dependency instead of a package. So it would require Intuit to update their dlls. Which, given their API quality, will probably never happen.

**Comment by nimisha84** [comment]
@sm-g We are planning to release the next version of SDK very soon by this month end/early next month with the latest .

@dcarl1- We use Nuget package for Json and since it is a required dependency by the SDK, we can only release updates to it when we release next version of the .Net SDK. I have already shared the signed dlls with you, so you should be able to use both the Json lib versions. If not, then you have the option to download the source code of the SDK and Update Nuget package and use those dlls in your code. So, you should not be blocked with the release of the SDK.
We will try our best to release the SDK with Updated Nuget package as soon as we can.

Regarding API, please share your feedback with us on live community and we will take it forward to the engineering team to improvise.
developer.intuit.com->Help

**Comment by dcarl1** [comment]
@nimisha84 Thanks for the signed DLLs, it is appreciated.

Completely for my own curiosity why would this specific package block upgrading to Newtonsoft.Json 10 when others, that also depend on 9, do not?

**Comment by nimisha84** [comment]
@dcarl1 - We have added the versioned NewtonSoft dll as an embedded dependency while creating the Nuget package. Will see if it can be decoupled for the future releases.
