### ISSUE TITLE
What kind of Account type and sub type is needed to create sales receipt and what kind for invoice?

### ISSUE THREAD

**Issue by pula2000** [intuit/QuickBooks-V3-DotNET-SDK#5]

**Comment by nimisha84** [comment]
Hi @pula2000 - Since this is more of an API related query, can you please post such queries on developer.intuit.com->Help?  It is easier for us to track API queries there and answer in detail.

For Invoice, you can refer the accounts used-
https://developer.intuit.com/docs/api/accounting/invoice - Search on AccountRef field.
For Sales Receipt-
https://developer.intuit.com/docs/api/accounting/salesreceipt

If you question is about what account is used for lines, then it is the account associated with the item attached to the lines. You will not see it on the invoice/sales receipt but internally that is used.
