### ISSUE TITLE
LineDetailTypeEnum.SalesItemLineDetail behavior changed

### ISSUE THREAD

**Issue by BrianVallelunga** [intuit/QuickBooks-V3-DotNET-SDK#53]
I just updated from the 4.x SDK to the 5.6 SDK package and found some changed behavior that is causing us problems.

We pull down invoices using the QueryService. Once we have an invoice, we loop through the line items, looking for only those that have a DetailType equal to LineDetailTypeEnum.SalesItemLineDetail. The problem occurs when a line item has no Product/Service assigned to it. In the 4.x SDK, the line item's DetailType is set as DescriptionOnly. In the 5.6 SDK, the DetailType is SalesItemLineDetail. I believe the previous behavior is correct.

Not only does the new SDK assign the DetailType incorrectly, but the ItemRef property also seems to be incorrectly assigned to the first/default value that our QB instance uses. It should have no ItemRef as far as I know, and certainly not the one being reported.

**Comment by nimisha84** [comment]
Thanks for the question. The earlier mapping/design implementation in api of having no itemref for description lines caused such line to show up incorrectly as Description line. The totals of such lines were never added up towards the invoice total. This was design flaw and we have tried to rectify that in api by assigning a default acc and creating them as salesitemlinedetail and adding it's total too if the amount is present against it. You can see that if the amount is not present in the current salesitemline and the itemref is a default one, then use that as a description line in your code.

5.6 version of SDK supports minorversion =28 by default and that is why you see the diff response.You can override the minorversion to use an older one which is compliant with your code's existing behavior.
Code to override-
ServiceContext serviceContext = Initializer.InitializeServiceContextQbo();
serviceContext.IppConfiguration.MinorVersion.Qbo = "4";

or manually configure the SDK for minor version 4:

    <configuration>   
        <intuit>
            <ipp>
                <!— ... other settings appear here  ... —>
                <minorVersion qbo=4></minorVersion>
                </ipp>
            </intuit>   
        <appSettings>       
            <!— ... oAuth tokens etc  ... —>
            </appSettings>
    </configuration>

This bug was fixed as part of minorversion 19 I believe. Try using  lower minorversion than 19 and see if you get the original response type of DescriptionLine if you do not want to modify your code. But if you use 26 or higher, you will see salesitemlinedetail in response. I can double check the minorversion for you bu I would say try toggling minorversions to see when you notice the changed response.

**Comment by BrianVallelunga** [comment]
Thanks for looking into this for me. Having the item report to be a SalesItemLineDetail is not an issue, as long as there exists a method to distinguish the items from those that have a product/service assigned and those that do not. As far as I understand it, some invoice line items are originally created as a passed-through billing expense from within QB. In the QB UI, these are not assigned any sort of product/service. Yet when I download the items, the product/service/itemref of the line items seem to be defaulted to the first one in our organization.

It seems like they need an itemref that's hardcoded to a "none" value of some sorts. I'm not an expert on the inner workings of the API, but from my point of view, we're getting back bad data.

**Comment by nimisha84** [comment]
Thanks for the feedback. I would that you should read about this change for minorversion =9. This was specific change made for Reimburse Charge/Billable Expense entities.
https://developer.intuit.com/hub/blog/2017/06/21/reimburse-charge-support-quickbooks-online-api

In cases where linked txn for Billable expense is present in the payload, do not use the account associated with the ItemRef but use the overriden value offered by the ItemAccountRef. This ItemAccountRef is supported only for the Billable expense use case so that apps do not get the account associated with the default item attached but rather use the correct value from ItemAccountRef.

Let me know if this helps.
