### ISSUE TITLE
ShipAddr is null when Billing Address is not set in QBO

### ISSUE THREAD

**Issue by malard** [intuit/QuickBooks-V3-DotNET-SDK#74]
If ONLY a ShipAddr is set for a Customer record, (either created originally via the API or directly in QBO) the Customer record returned via GetDataService().FindById() returns null

It should return the PhysicalAddress record that clearly exists.

It is not clear to me if this is an API bug or an SDK issue.

**Comment by nimisha84** [comment]
It should be an API error most probably. Please enable logs so that we can see what request and response is being generated -
Follow any of the below steps:
To manage exception handling in your code:

- Enable request/response logs by overriding the configuration: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

If you still do not see error details, enable logging in code using these three lines:

ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator);
serviceContext.IppConfiguration.Logger.RequestLog.EnableRequestResponseLogging = true;
serviceContext.IppConfiguration.Logger.RequestLog.ServiceRequestLoggingLocation = @"C:\IdsLogs";

- Set trace logging to verbose mode: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

- Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.

**Comment by malard** [comment]
Hi, while i can go through the effort to do this, i think i've been fairly succinct already in providing enough information for you to debug against. While I am content to do this at some point in the near future, surely any attempt to resolve this will require you to simulate a Customer read in your own dev environment and as such you could capture these at the same time?

**Comment by ServicePal** [comment]
Welcome to the party pal!
Now sit back and enjoy "QuickBooks Online API **consistently** experiencing intermittent issues"

**Comment by nimisha84** [comment]
PLEX-1392 bug is created for API team. You can track it on the bug tracker here https://help.developer.intuit.com/s/bug-tracker-page.
@ServicePal - Please let us know what issues you are facing and I can help with those. But, for API issues as you continue to do, please report on our help page as this Issues page is only for SDK issues. 

Thanks.
